@startuml
skinparam linetype ortho

package model {

    interface GridEntity {
        +onHit(attacker : Player, defender : Player, x : int, y : int)
        +isDestructible() : boolean
        +getType() : EntityType
    }

    interface GameListener {
        +turnEnded(attacker : Player, resultSummary : Map<Coordinate, String>)
        +onCellUpdated(player : Player, coord : Coordinate)
        +onScanResult(player : Player, results : List<ScanResult>)
        +onShipSunk(player : Player)
        +onGameOver(winner : Player)
        +displayTurnSummary(attacker : Player, summary : Map<Coordinate,String>)
    }

    class GameConfig {
        -m_nickname : String
        -m_size : integer
        -m_islandMode : boolean
        -m_gridEntityPlacement : Map<EntityType, Coordinate>
        + <<create>> GameConfig()
        +getNickname() : String
        +getSize() : Integer
        +isIslandMode() : boolean
        +getGridEntityPlacement() : Map<EnnumEntity, Coordinate>
        +addEntityPlacement(coord : Coordinate, entityType : EntityType)
    }

    enum EntityType <<enumerate>>{
                AIRCRAFT_CARRIER
                CRUISER
                SUBMARINE
                TORPEDO
                DESTROYER
                BLACK_HOLE
                STORM
                BOMB
                SONAR
                NEW_BLACKHOLE
                NEW_STORM
                NEW_BOMB
                NEW_SONAR
    }

    class Game {
        -m_humanPlayer : Player
        -m_computerPlayer : ComputerPlayer
        -m_currentPlayerIndex : int

        <<create>> Game(config : GameConfig)

        +placeEntity(Map<EntityType, List<Coordinate> >)

        +processComputerAttack()
        +processAttack(attacker : Player, weapon : Weapon, target : Coordinate)
        +processOffensiveAttack(attacker : Player, defender : Player, target : List<Coordinate>)
        +processShot(attacker : Player, defender : Player, x : int, y : int)
        +processScan(attacker : Player, defender : Player, target : List<Coordinate>)

        +exploreIsland(player : Player, coord : Coordinate)

        +isGameOver() : boolean
        +getWinner() : Player
        +addListener(l : GameListener)
        +removeListener(l : GameListener)
        +notifyTurnEnded(attacker : Player, summary : Map<Coordinate,String>)
    }

    package player{
        abstract Player <<abstract>>{
            -m_name : String
            -m_ownGrid : Grid
            -m_nbBoatRemaining : integer
            -m_trackingGrid : Grid
            -m_weaponFactory : WeaponFactory

            +<<create>> Player(config : GameConfig)
            +placeEntity(Map<EntityType, List<Coordinate> >)
            +getOwnGrid() : Grid
            +getTrackingGrid() : Grid
            +addWeapon(w : Weapon)
            +markMiss(coord : Coordinate)
            +getEntityFromCoord(coord : Coordinate) : GridEntity
            +receiveShot(coord : Coordinate)
            +triggerTornado(coord : Coordinate)
            +loseOneBoat()
            +hasLost() : boolean
        }

        class ComputerPlayer extends Player{
            +<<create>> ComputerPlayer(config : GameConfig)
            + choseCoord() : Coordinate
            + choseWeapon() : Weapon
        }
    }


    package map{
        class Grid {
            -m_size : integer
            -m_trapFactory : TrapFactory
            -m_islandItemFactory : IslandItemFactory
            +<<create>> Grid(entityPosition : Map<EntityType, List<Coordinate> >, gridSize : integer)
            +placeEntity(Map<EntityType, List<Coordinate> >)
            +getCell(x : int, y : int) : Cell
            +isInside(coord : Coordinate) : boolean
            +hit(x : int, y : int)
            +desactiveTrap(x : int, y : int)
            +markMiss(x : int, y : int)
            +triggerTornado(coord : Coordinate)
            +getEntityFromCoord(coord : Coordinate) : GridEntity
        }

        class Cell {
            -m_entity : GridEntity
            -m_hit : boolean
            -m_miss : boolean
            +<<create>> Cell()
            +getEntity() : GridEntity
            +setEntity(e : GridEntity)
            +setHit(boolean)
            +setMiss(boolean)
        }
    }

    class Coordinate {
        -m_x : int
        -m_y : int
        +<<create>> Coordinate(x : integer, y : integer)
        +getX() : int
        +getY() : int
    }

    class ScanResult {
        -m_coord : Coordinate
        -m_symbol : EntityType
        +<<create>> ScanResult(coord : Coordinate, content : EntityType)
        +getCoord() : Coordinate
        +getSymbol() : String
    }


    package boat{
            enum BoatType <<enumerate>> {
                AIRCRAFT_CARRIER
                CRUISER
                DESTROYER
                SUBMARINE
                TORPEDO
            }
            ' Interface design patern : Factory
            interface BoatFactory <<interface>>{
                + createBoat(BoatType): Boat
            }

            class SimpleBoatFactory implements BoatFactory{
                + createBoat(BoatType): Boat
            }

            ' un bateau est une entité de la grille
            interface Boat <<interface>> implements model.GridEntity {
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }
            class Submarine implements Boat{
                - m_size: Integer
                - m_nbReceiveShot : integer

                + <<create>> Submarine()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Torpedo implements Boat{
                - m_size: Integer
                - m_nbReceiveShot : integer

                + <<create>> Torpedo()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Destroyer implements Boat{
                - m_size: Integer
                - m_nbReceiveShot : integer

                + <<create>> Destroyer()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Cruiser implements Boat{
                - m_size: Integer
                - m_nbReceiveShot : integer

                + <<create>> Cruiser()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class AircraftCarrier implements Boat{
                - m_size: Integer
                - m_nbReceiveShot : integer

                + <<create>> AircraftCarrier()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            BoatFactory ..> Boat : create
            SimpleBoatFactory ..> Boat : create

            BoatFactory .up.> BoatType : <<use>>
            SimpleBoatFactory .up.> BoatType : <<use>>
    }

    package weapon{
        interface Weapon {
            +generateTargets(coord : Coordinate, grid : Grid) : List<Coordinate>
            +getName() : String
        }
        class WeaponFactory{
            +<<create>> WeaponFactory()
            +createSonar() : Sonar
            +createBomb() : Bomb
        }
        class Missile {
            +<<create>> Missile()
            +generateTargets(coord, grid)
        }

        class Bomb {
            - m_useLeft: Integer
            +<<create>> Bomb()
            +generateTargets(coord, grid)
        }

        class Sonar {
            - m_useLeft: Integer
            +<<create>> Sonar()
            +generateTargets(coord, grid)
        }
    }

    package entity{
        package trap{
            interface Trap{
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                +getType() : EntityType
            }
            class BlackHole implements Trap{
                 -m_type : EntityType
                 +<<create>> BlackHole(type : EntityType)
                 +onHit(attacker : Player, defender : Player, x : int, y : int)
                 +getType() : EntityType
             }

             class Storm implements Trap{
                 -m_turnsLeft: Integer
                 -m_type : EntityType
                 +<<create>> Storm()
                 +onHit(attacker : Player, defender : Player, x : int, y : int)
                 +getType() : EntityType
                 +modifyCoordinates(coordinates: Coordinates): Coordinates
             }

             class TrapFactory{
                +<<create>> TrapFactory()
                +createStorm() : Storm
                +createBlackHole() : BlackHole
             }
        }

        package newIslandItem{
            class IslandItemFactory {
                +<<create>> IslandItemFactory()
                +createNewItemStorm() : NewStorm
                +createNewItemBomb() : NewBomb
                +createNewItemSonar() : NewSonar
                +createNewItemBlackHole() : NewBlackHole
            }

            class NewBomb{
                -m_type : EntityType
                +<<create>> NewBomb()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                +getType() : EntityType
            }

            class NewSonar{
                -m_type : EntityType
                +<<create>> NewSonar()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                +getType() : EntityType
            }

            class NewBlackHole{
                -m_type : EntityType
                -m_trapFactory : TrapFactory
                +<<create>> NewBlackHole()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                +getType() : EntityType
             }

            class NewStorm{
                -m_type : EntityType
                -m_trapFactory : TrapFactory
                +<<create>> NewStorm()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                +getType() : EntityType
            }
        }
    }
}

package view {
    class ConfigView {
        -m_controller : GameController
        -m_nextStepButton : JButton
        -m_IslandMode : JButton
        -m_gridSize : JComboBox<Integer>
    }
    class PlaceEntityView {
        -m_controller : GameController
        -m_playButton : JButton
        -m_validePlacement : JButton
        -m_gridPlacement : GridPanel
    }
    class GameOverView{
        -m_exitButton : JButton
        -m_restartButton : JButton
        -m_score : JLabel
        -m_controller : GameController
    }

    class GameView {
        -m_controller : GameController
        -m_gridPanelPlayer : GridPanel
        -m_gridPanelTracking : GridPanel
        -m_valideShot : JButton
        -m_statusPanel : StatusPanel

        +turnEnded(attacker : Player, resultSummary : Map<Coordinate, String>)
        +onCellUpdated(cell : Cell, coord : Coordinate)
        +onScanResult(player : Player, results : List<ScanResult>)
        +onShipSunk(player : Player)
        +onGameOver(winner : Player)
        +displayTurnSummary(attacker : Player, summary : Map<Coordinate,String>)
    }

    class GridPanel {
        -m_controller : GameController
        +updateCell(coord : Coordinate, symbol : String)
        +repaint(coord : Coordinate, cell : Cell)
    }

    class StatusPanel {
        +setMessage(msg : String)
    }

    class CellView{
        <<create>> CellView(cell : Cell, controller : GameController)
        +repaint(cell : Cell)
    }
}

package "Controller" {

    class GameController {
        -m_game : Game
        -m_gameConfig : GameConfig
        -m_configView : ConfigView
        -m_placeEntityView : PlaceEntityView
        -m_gameOverView : GameOverView
        -m_gameView : GameView
        -m_cellSelected : Coordinate
        -m_weaponSelected : EntityType

        +callGameView()
        +callConfigView()
        +callPlaceEntityView()
        +callGameOverView()

        +onCellClicked(coord : Coordinate)
        +onWeaponSelected(weapon : Weapon)
        +setCellSelected(coord : Coordinate)
        +checkPlacement(coords : List<Coordinate>, entityType : EntityType, size : integer) : boolean
    }
}

GridEntity <|.. BlackHole
GridEntity <|.. Storm

Weapon <|.. Missile
Weapon <|.. Bomb
Weapon <|.. Sonar

Player "1" *--> "1\n ownGrid" Grid
Player "1" *--> "1\n trackingGrid" Grid
Player "1" *--> "*\n_weapons" Weapon
Player "1" *--> "1\n weaponFactory" WeaponFactory
Player --> ScanResult : <<use>>
Player --> Coordinate : <<use>>
Player --> GameConfig : <<use>>

ComputerPlayer --> Coordinate : <<use>>
ComputerPlayer --> Weapon : <<use>>
ComputerPlayer --> GameConfig : <<use>>

Grid "1" *--> "*\n_cells" Cell
Grid "1" *--> "1\n" TrapFactory
Grid "1" *--> "1\n" IslandItemFactory
Grid "1" *--> "0..*\n_ownBoats" Boat : <<contain>>
Grid --> Coordinate : <<use>>
Grid --> BoatFactory : <<use>>
Grid --> GridEntity : <<use>>
Grid --> EntityType : <<use>>

Game "1" *--> "1\n humanPlayer" Player
Game "1" *--> "1\n computerPlayer" Player
Game "1" --> "1" GameConfig : <<create>>
Game "1" --> "1..*\n_listeners" GameListener : notify >
Game --> Weapon : <<uses>>
Game --> ScanResult : <<uses>>
Game --> Coordinate : <<uses>>

WeaponFactory --> Sonar : <<use>>
WeaponFactory --> Bomb : <<use>>

TrapFactory --> Storm : <<use>>
TrapFactory --> BlackHole : <<use>>
IslandItemFactory --> NewBlackHole : <<use>>
IslandItemFactory --> NewBomb : <<use>>
IslandItemFactory --> NewSonar : <<use>>
IslandItemFactory --> NewStorm : <<use>>

NewStorm --> TrapFactory : <<use>>
NewBlackHole --> TrapFactory : <<use>>
NewBomb --> WeaponFactory : <<use>>
NewSonar --> WeaponFactory : <<use>>

Cell "1" *--> "0..1" GridEntity : <<contain>>

GameConfig --> EntityType : <<uses>>
GameConfig --> Coordinate : <<uses>>

GridEntity --> Player : <<Player>>

ScanResult --> EntityType : <<create>>

GameController o--> Game : controls
GameController --> GameView : updates
GameController --> ConfigView : call
GameController --> PlaceEntityView : call
GameController --> GameOverView : call
GameView --> GameController : user actions

GameListener <|.. GameView

GameView *--> "2"GridPanel : <<contain>>
GameView --> StatusPanel

GridPanel --> Coordinate : <<uses>>
GridPanel *--> "*\n_CellView" CellView : <<contain>>

@enduml
