@startuml
skinparam linetype ortho

title Architecture MVC Bataille Navale – Modèle complet

' ============================================================
'                       PACKAGES
' ============================================================

package "Model" {

    ' ----------------------
    ' Interfaces
    ' ----------------------

    interface GridEntity {
        +onHit(attacker : Player, defender : Player, x : int, y : int)
        +isDestructible() : boolean
        +displaySymbol() : String
    }



    interface GameListener {
        +turnEnded(attacker : Player, resultSummary : Map<Coordinate, String>)
        +onCellUpdated(player : Player, coord : Coordinate)
        +onScanResult(player : Player, results : List<ScanResult>)
        +onShipSunk(player : Player)
        +onGameOver(winner : Player)
        +displayTurnSummary(attacker : Player, summary : Map<Coordinate,String>)
    }

    ' ----------------------
    ' Core classes
    ' ----------------------

    class Game {
        -players : List<Player>
        -currentPlayerIndex : int
        -listeners : List<GameListener>

        +placeBoats()

        +processComputerAttack()
        +processAttack(attacker : Player, weapon : Weapon, target : Coordinate)
        +processOffensiveAttack(attacker : Player, defender : Player, target : List<Coordinate>)
        +processShot(attacker : Player, defender : Player, x : int, y : int)
        +processScan(attacker : Player, defender : Player, target : List<Coordinate>)

        +handleStorm(attacker : Player, defender : Player, x : int, y : int)

        +exploreIsland(player : Player, coord : Coordinate)

        +isGameOver() : boolean
        +getWinner() : Player
        +addListener(l : GameListener)
        +removeListener(l : GameListener)
        +notifyTurnEnded(attacker : Player, summary : Map<Coordinate,String>)
    }

    package player{
        abstract Player <<abstract>>{
            -name : String
            -ownGrid : Grid
            -nbBoatRemaining : integer
            -trackingGrid : Grid
            -weapons : List<Weapon>

            +placeBoats()
            +getOwnGrid() : Grid
            +getTrackingGrid() : Grid
            +addWeapon(w : Weapon)
            +markMiss(coord : Coordinate)
            +getEntityFromCoord(coord : Coordinate) : GridEntity
            +receiveShot(coord : Coordinate)
            +triggerTornado(coord : Coordinate)
            +loseOneBoat()
            +hasLost() : boolean
        }

        class ComputerPlayer extends Player{
            + choseCoord() : Coordinate
            + choseWeapon() : Weapon
        }
    }


    package Map{
        class Grid {
            -cells : Cell[][]
            -ownBoats : List <Boat>
            -size : integer
            +placeBoats()
            +getCell(x : int, y : int) : Cell
            +isInside(coord : Coordinate) : boolean
            +hit(x : int, y : int)
            +desactiveTrap(x : int, y : int)
            +markMiss(x : int, y : int)
            +triggerTornado(coord : Coordinate)
            +getEntityFromCoord(coord : Coordinate) : GridEntity
        }

        class Cell {
            -entity : GridEntity
            -hit : boolean
            -miss : boolean

            +getEntity() : GridEntity
            +setEntity(e : GridEntity)
            +setHit(boolean)
            +setMiss(boolean)
        }

    }



    class Coordinate {
        -x : int
        -y : int
        +getX() : int
        +getY() : int
    }

    class ScanResult {
        -coord : Coordinate
        -symbol : String
        +getCoord() : Coordinate
        +getSymbol() : String
    }


    package Boat{
            enum BoatType <<enumerate>> {
                AIRCRAFT_CARRIER
                CRUISER
                DESTROYER
                SUBMARINE
                TORPEDO
            }
            ' Interface design patern : Factory
            interface BoatFactory <<interface>>{
                + createBoat(BoatType): Boat
            }

            class SimpleBoatFactory implements BoatFactory{
                + createBoat(BoatType): Boat
            }

            ' un bateau est une entité de la grille
            interface Boat <<interface>> implements Model.GridEntity {
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }
            class Submarine implements Boat{
                - size: Integer
                - nbReceiveShot : integer

                + <<create>> Submarine()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Torpedo implements Boat{
                - size: Integer
                - nbReceiveShot : integer

                + <<create>> Torpedo()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Destroyer implements Boat{
                - size: Integer
                - nbReceiveShot : integer

                + <<create>> Destroyer()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class Cruiser implements Boat{
                - size: Integer
                - nbReceiveShot : integer

                + <<create>> Cruiser()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            class AircraftCarrier implements Boat{
                - size: Integer
                - nbReceiveShot : integer

                + <<create>> AircraftCarrier()
                +onHit(attacker : Player, defender : Player, x : int, y : int)
                + isSunk(): boolean
                + hit(index: Integer)
                + getSize(): Integer
                + getName(): String
            }

            BoatFactory ..> Boat : create
            SimpleBoatFactory ..> Boat : create

            BoatFactory .up.> BoatType : <<use>>
            SimpleBoatFactory .up.> BoatType : <<use>>
    }

    ' ----------------------
    ' Weapons
    ' ----------------------

    package weapon{
        interface Weapon {
            +generateTargets(coord : Coordinate, grid : Grid) : List<Coordinate>
            +getName() : String
        }
        class Missile {
            +generateTargets(coord, grid)
        }

        class Bomb {
            - useLeft: Integer
            +generateTargets(coord, grid)
        }

        class Sonar {
            - useLeft: Integer
            +generateTargets(coord, grid)
        }
    }


    ' ----------------------
    ' Grid Entities
    ' ----------------------

    package Entity{
        class BlackHole {
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
        }

        class Storm {
            - turnsLeft: Integer
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
            + modifyCoordinates(coordinates: Coordinates): Coordinates
        }

        interface IslandEntity {
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
        }

        class newBomb implements IslandEntity{
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
        }

        class newSonar implements IslandEntity{
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
        }

        class newBlackHole implements IslandEntity{
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
         }

        class newTornado implements IslandEntity{
            +onHit(attacker : Player, defender : Player, x : int, y : int)
            +displaySymbol()
        }
    }



}

' ============================================================
'                   VIEW PACKAGE
' ============================================================

package "View" {

    class GameView {
        -controller : GameController
        -gridPanelPlayer : GridPanel
        -gridPanelTracking : GridPanel
        -statusPanel : StatusPanel

        +turnEnded(attacker : Player, resultSummary : Map<Coordinate, String>)
        +onCellUpdated(cell : Cell, coord : Coordinate)
        +onScanResult(player : Player, results : List<ScanResult>)
        +onShipSunk(player : Player)
        +onGameOver(winner : Player)
        +displayTurnSummary(attacker : Player, summary : Map<Coordinate,String>)
    }

    class GridPanel {
        +updateCell(coord : Coordinate, symbol : String)
        +repaint(coord : Coordinate, cell : Cell)
    }

    class StatusPanel {
        +setMessage(msg : String)
    }

    class CellView{
        <<create>> CellView(cell : Cell, controller : GameController)
        +repaint(cell : Cell)
    }
}

' ============================================================
'                CONTROLLER PACKAGE
' ============================================================

package "Controller" {

    class GameController {
        -game : Game
        -view : GameView
        -cellSelected : Coordinate

        +onCellClicked(coord : Coordinate)
        +onWeaponSelected(weapon : Weapon)
        +setCellSelected(coord : Coordinate)
    }
}

' ============================================================
'                  RELATIONS (MODEL)
' ============================================================

GridEntity <|.. Ship
GridEntity <|.. BlackHole
GridEntity <|.. Storm
GridEntity <|.. IslandEntity

Weapon <|.. Missile
Weapon <|.. Bomb
Weapon <|.. Sonar

Player "1" *--> "1" Grid : ownGrid
Player "1" *--> "1" Grid : trackingGrid
Player "1" *--> "*\n_weapons" ScanResult
Grid "1" *-- "*" Cell
Grid o--> Coordinate
Game "1" o-- "*" Player
Game "1" --> "*" GameListener : notifies >

Cell "1" --> "0..1" GridEntity

Game --> Weapon : <<uses>>
Game --> ScanResult : <<uses>>
Game --> Coordinate : <<uses>>
Game --> Player : orchestrates

' ============================================================
'                 MVC RELATIONSHIPS
' ============================================================

GameController --> Game : controls
GameController --> GameView : updates
GameView --> GameController : user actions

Game --> GameView : <<listener>> turnEnded()
GameListener <|.. GameView

GameView *--> "2"GridPanel : <<contient>>
GameView --> StatusPanel

GridPanel --> Coordinate : <<uses>>
GridPanel *--> "*\n_CellView" CellView : <<contient>>

@enduml
