@startuml
skinparam linetype ortho
package model.boat {

    interface Boat {
        + boolean isSunk()
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + Integer getSize()
        + EntityType getType()
        + Integer getSegmentsHit()
        + void registerToGrid(grid : Grid)
    }

    class BoatFactory {
        + <<Create>> BoatFactory()
        + AirCraftCarrier createAirCraftCarrier() : AirCraftCarrier
        + Cruiser createCruiser() : Cruiser
        + Destroyer createDestroyer() : Destroyer
        + Submarine createSubmarine() : Submarine
        + Torpedo createTorpedo() : Torpedo
    }

    enum BoatType {
        + AIRCRAFT_CARRIER
        + CRUISER
        + DESTROYER
        + SUBMARINE
        + TORPEDO
    }

    package type {
        class AirCraftCarrier {
            - {static} int m_AIRCRAFTCARRIER_SIZE
            - Integer m_size
            - boolean[] m_hits
            - EntityType m_type
            + <<Create>> AirCraftCarrier()
            + boolean isSunk()
            + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
            + Integer getSize()
            + EntityType getType()
            + Integer getSegmentsHit()
            + void registerToGrid(grid : Grid)
        }

        class Cruiser {
            - {static} int m_CRUISER_SIZE
            - Integer m_size
            - boolean[] m_hits
            - EntityType m_type
            + <<Create>> Cruiser()
            + boolean isSunk()
            + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
            + EntityType getType()
            + Integer getSize()
            + Integer getSegmentsHit()
            + void registerToGrid(grid : Grid)
        }

        class Destroyer {
            - {static} int m_DESTROYER_SIZE
            - Integer m_size
            - boolean[] m_hits
            - EntityType m_type
            + <<Create>> Destroyer()
            + boolean isSunk()
            + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
            + Integer getSize()
            + EntityType getType()
            + Integer getSegmentsHit()
            + void registerToGrid(grid : Grid)
        }

        class Submarine {
            - {static} int m_SUBMARINE_SIZE
            - Integer m_size
            - boolean[] m_hits
            - EntityType m_type
            + <<Create>> Submarine()
            + boolean isSunk()
            + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
            + Integer getSize()
            + EntityType getType()
            + Integer getSegmentsHit()
            + void registerToGrid(grid : Grid)
        }

        class Torpedo {
            - {static} int m_Torpedo_SIZE
            - Integer m_size
            - boolean[] m_hits
            - EntityType m_type
            + <<Create>> Torpedo()
            + boolean isSunk()
            + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
            + Integer getSize()
            + EntityType getType()
            + Integer getSegmentsHit()
            + void registerToGrid(grid : Grid)
        }
    }
}
package model.entity.island {

    class NewStorm {
        - EntityType m_type
        - Integer m_size
        - List<IslandListener> m_listeners
        + <<Create>> NewStorm()
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + EntityType getType()
        + Integer getSize()
        + void attachListener(listener : IslandListener)
        + void notifyListener(entity : Trap, player : Player)
        + boolean isSunk()
        + void registerToGrid(grid : Grid)
    }

    class NewSonar {
        - EntityType m_type
        - Integer m_size
        + <<Create>> NewSonar()
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + EntityType getType()
        + Integer getSize()
        + boolean isSunk()
        + void registerToGrid(grid : Grid)
    }

    class NewBomb {
        - EntityType m_type
        - Integer m_size
        - List<IslandListener> m_listeners
        + <<Create>> NewBomb()
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + EntityType getType()
        + Integer getSize()
        + void attachListener(listener : IslandListener)
        + void notifyListener(weaponType : EntityType)
        + boolean isSunk()
        + void registerToGrid(grid : Grid)
    }

    class NewBlackHole {
        - EntityType m_type
        - Integer m_size
        - List<IslandListener> m_listeners
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + EntityType getType()
        + Integer getSize()
        + boolean isSunk()
        + void attachListener(listener : IslandListener)
        + void notifyListener(entity : Trap, player : Player)
        + void registerToGrid(grid : Grid)
    }
    class IslandItemFactory {
        + <<Create>> IslandItemFactory()
        + NewStorm createNewItemStorm() : NewStorm
        + GridEntity createNewItemBomb() : GridEntity
        + GridEntity createNewItemSonar() : GridEntity
        + GridEntity createNEwItemBlackHole() : GridEntity
    }
}

package model.game {

    class Game {
        - TrapFactory m_trapFactory
        - boolean m_gameFinished
        - HumanPlayer m_humanPlayer
        - ComputerPlayer m_computerPlayer
        - Player m_currentPlayer
        - Weapon m_currentWeaponUsed
        - GameConfiguration m_game
        - int m_turnNumber
        - List<GameListener> m_listeners
        - List<IslandListener> m_islandListeners
        - StringBuilder m_historyLog
        + <<Create>> Game(config : GameConfiguration)
        + String getHistory()
        - addToHistory(action : String)
        + processComputerAttack()
        + processAttack(attacker : Player, weapon : Weapon, coord : Coordinate)
        - Coordinate generateRandomCoordinate(gridSize : int)
        - processOffensiveAttack(attacker : Player, defender : Player, targets : List<Coordinate>)
        - processShot(attacker : Player, defender : Player, x : int, y : int)
        - processScan(attacker : Player, defender : Player, targets : List<Coordinate>)
        + boolean isGameOver()
        - boolean checkGameOver()
        + Player getWinner()
        + Player getOpponent(p : Player)
        + nextTurn()
        + displayGridPlayer()
        + addListener(listener : GameListener)
        + addIslandListener(listener : IslandListener)
        + handleMiss(defender : Player, x : int, y : int)
        + handleHit(defender : Player, coord : Coordinate)
        + handleBlackHoleHit(defender : Player, coord : Coordinate)
        + handleShipSunk(defender : Player, boat : Boat)
        + HumanPlayer getHumanPlayer()
        + ComputerPlayer getComputerPlayer()
        + incrementTurnNumber()
        - processIslandSearch(attacker : Player, defender : Player, coord : Coordinate)
        - notifyPlaceTrapRequest(trap : Trap, player : Player)
        - notifyWeaponFound(type : EntityType)
        + notifyTrapPlacementError()
        + boolean tryPlaceTrap(player : Player, trap : Trap, coord : Coordinate)
    }

    interface GameMediator {
        + handleShipSunk(defender : Player, sunkBoat : Boat)
        + handleHit(defender : Player, hitCoordinate : Coordinate)
        + handleBlackHoleHit(defender : Player, hitCoordinate : Coordinate)
        + notifyTrapPlacementError()
    }

    class GameConfiguration {
        - String m_nickName
        - Integer m_gridSize
        - Map<EntityType,List<Coordinate>> m_gridEntityPlacement
        - boolean m_isIslandMode
        + <<Create>> GameConfiguration(gridSize : Integer, boatsPlacement : Map<EntityType,List<Coordinate>>, isIslandMode : boolean, name : String)
        + Integer getGridSize()
        + String getNickName()
        + Map<EntityType,List<Coordinate>> getGridEntityPlacement()
        + boolean isIslandMode()
    }
}

package model.map {

    class Cell {
        - GridEntity m_entity
        - boolean m_hitBoat
        - boolean m_hitTrap
        - boolean m_miss
        - Integer m_indexInEntity
        + <<Create>> Cell()
        + GridEntity getEntity()
        + void setEntity(e : GridEntity)
        + void setHit(hit : boolean)
        + void setMiss(miss : boolean)
        + boolean isHit()
        + boolean isFilled()
        + Integer getIndexInEntity()
        + void setIndexInEntity(index : Integer)
        + void setHitBoat(status : boolean)
        + EntityType getTypeEntityFromCell(coord : Coordinate)
    }

    class Grid {
        - Integer m_size
        - Cell[][] m_cells
        - List<Boat> m_ownBoats
        - IslandItemFactory m_islandItemFactory
        - BoatFactory m_boatFactory
        - TrapFactory m_trapFactory
        - boolean m_islandMod
        - List<Coordinate> m_islandCoordinates
        + <<Create>> Grid(gridSize : Integer, isIsland : boolean)
        + void getAllCoordsFromIsland()
        + boolean coordIsinIsland(coord : Coordinate)
        + void placeTrap(trap : Trap, coord : Coordinate)
        + void placeEntity(entityPosition : Map<EntityType, List<Coordinate>>)
        + boolean placeSingleEntity(entity : GridEntity, coordinates : List<Coordinate>)
        + void addBoatToMemory(boat : Boat)
        + GridEntity createEntityFromType(type : EntityType)
        + Cell getCell(x : int, y : int)
        + boolean isInside(coord : Coordinate)
        + boolean isInside(x : int, y : int)
        + void hit(x : int, y : int, defender : Player, attacker : Player)
        + void markMiss(x : int, y : int)
        + void markHitBoat(coord : Coordinate)
        + GridEntity getEntityFromCoord(coord : Coordinate)
        + EntityType getTypeEntityFromGrid(coord : Coordinate)
        + int getSize()
        + boolean isAlreadyHit(x : int, y : int)
        + void randomPlacementEntity(type : EntityType)
        - List<Integer> getIslandPositions()
        + boolean cellAlreadyFilled(x : int, y : int)
        + void displayGrid()
        + List<Boat> getOwnBoats()
        + void setIslandMod(isIslandMod : boolean)
        + boolean isValidPosition(coord : Coordinate, size : int, horizontal : boolean)
        + void initIslandItems()
        + boolean isPosOnIsland(x : int, y : int)
        + GridEntity realTrap(trap : Trap)
        + void setCellHitAt(x : Integer, y : Integer, hit : boolean)
    }
}

package model.player {

    abstract class Player {
        - String m_name
        - Grid m_ownGrid
        - Grid m_shotGrid
        - Integer m_nbBoatRemaning
        - GameMediator m_mediator
        - IslandListener m_islandListener
        - List<Weapon> m_availableWeapons
        - List<Trap> m_traps
        - Coordinate m_lastMove
        - int m_totalShipSegments
        - TrapFactory m_trapFacto
        - WeaponFactory m_weaponFacto
        - List<IslandListener> m_listeners
        - int mTornadoTurnsRemaining
        + <<Create>> Player(config : GameConfiguration)
        + void placeEntity(entityPlacement : Map<EntityType, List<Coordinate>>)
        + void decrementTornadoEffect()
        + Grid getOwnGrid()
        + Grid getShotGrid()
        + Integer getGridSize()
        + String getNickName()
        + void loseOneBoat()
        - int calculateTotalShipSegments()
        + void updateTotalShipSegments()
        + void triggerTornadoEffect()
        + boolean isUnderTornadoInfluence()
        + Cell getTargetCell(x : int, y : int)
        + int getTotalShipSegments()
        + void setLastMove(coord : Coordinate)
        + boolean hasLost()
        + void receiveShot(coord : Coordinate, attacker : Player)
        + void setMediator(mediator : GameMediator)
        + void notifySunkStatus(sunkBoat : Boat)
        + void notifyHit(defender : Player, coord : Coordinate)
        + void notifyBlackHoleHit(defender : Player, coord : Coordinate)
        + EntityType getTypeEntityAt(coord : Coordinate)
        + Trap findTrap(type : EntityType)
        + void findWeapon(type : EntityType)
        + String getName()
        + Map<String, Integer> getShipStatusStats()
        + Map<String, Integer> getHitAccuracyStats(defender : Player)
        + String getLastMove()
        + String getWeaponUsesLeft(weaponType : String)
        + Weapon getWeapon(weaponType : String)
        + void addFoundItem(type : EntityType)
        + void placeNewTrap(trap : Trap, coord : Coordinate)
        + void setHitCellAt(x : Integer, y : Integer, hit : boolean)
        + Cell getCellAt(x : Integer, y : Integer)
        + EntityType getTypeOfGridEntityFromCoord(x : Integer, y : Integer)
        + {abstract} boolean placeFoundTrap(trap : Trap, coord : Coordinate, grid : Grid)
    }

    class HumanPlayer {
        - WeaponFactory m_weaponFactory
        + <<Create>> HumanPlayer(config : GameConfiguration)
        + boolean placeFoundTrap(trap : Trap, coord : Coordinate, grid : Grid)
    }

    class ComputerPlayer {
        - WeaponFactory m_weaponFactory
        + <<Create>> ComputerPlayer(config : GameConfiguration)
        + void placeEntity(entityPlacement : Map<EntityType,List<Coordinate>>)
        + Coordinate choseCoord(opponentGrid : Grid)
        + Weapon choseWeapon()
        + void placeRandomEntities(entityCounts : Map<EntityType,Integer>)
        + boolean placeFoundTrap(trap : Trap, coord : Coordinate, grid : Grid)
    }
}

package model.trap {

    interface Trap {
        + EntityType getType() : EntityType
        + void activate()
    }

    class BlackHole {
        - Integer m_size
        - boolean m_activate
        - boolean m_isConsumed
        - EntityType m_type
        + <<Create>> BlackHole(islandMod : boolean)
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + EntityType getType()
        + Integer getSize()
        + void activate()
        + boolean isSunk()
        + void registerToGrid(grid : Grid)
    }

    class Storm {
        - Integer m_size
        - boolean m_isConsumed
        - boolean m_activate
        - Integer turnsLeft
        - EntityType m_type
        + <<Create>> Storm(islandMod : boolean)
        + void onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
        + Coordinate modifyCoordinates(size : Integer)
        + EntityType getType()
        + Integer getSize()
        + void activate()
        + boolean isSunk()
        + void registerToGrid(grid : Grid)
    }

    class TrapFactory {
        + <<Create>> TrapFactory()
        + GridEntity createStorm(p : boolean)
        + GridEntity createBlackHole(p : boolean)
    }
}

package model.weapon {

    interface Weapon {
        + List<Coordinate> generateTargets(coord : Coordinate, gridSize : int)
        + String getName()
        + Integer getUsesLeft()
        + void setUsesLeft()
        + void use()
        + EntityType getType()
        + boolean isOffensive()
    }

    class Sonar {
        - Integer m_useLeft
        + <<Create>> Sonar()
        + List<Coordinate> generateTargets(coord : Coordinate, gridSize : int)
        + String getName()
        + boolean isOffensive()
        + Integer getUsesLeft()
        + void setUsesLeft()
        + void use()
        + EntityType getType()
    }

    class Bombe {
        - Integer m_useLeft
        + List<Coordinate> generateTargets(coord : Coordinate, gridSize : int)
        + String getName()
        + Integer getUsesLeft()
        + void setUsesLeft()
        + boolean isOffensive()
        + void use()
        + EntityType getType()
    }

    class Missile {
        - {static} Integer m_unlimited_uses
        + <<Create>> Missile()
        + List<Coordinate> generateTargets(coord : Coordinate, gridSize : int)
        + String getName()
        + boolean isOffensive()
        + void setUsesLeft()
        + Integer getUsesLeft()
        + void use()
        + EntityType getType()
    }

    class WeaponFactory {
        + <<Create>> WeaponFactory()
        + Sonar createSonar()
        + Bombe createBomb()
        + Missile createMissile()
    }
}

class model.Coordinate {
    - Integer m_row
    - Integer m_column
    + <<Create>> Coordinate(row : Integer, column : Integer)
    + String toString()
    + int getX()
    + Integer getY()
    + Coordinate getRelative(drow : Integer, dcol : Integer)
    + boolean equals(o : Object)
    + int hashCode()
}

class model.ScanResult {
    - Coordinate m_coord
    - EntityType m_type
    + <<Create>> ScanResult(coord : Coordinate, type : EntityType)
    + Coordinate getCoord()
    + EntityType getType()
}

interface model.GameListener {
    + onScanResult(player : Player, scannedArea : List<Coordinate>, results : List<ScanResult>)
    + onGameOver(winner : Player)
    + turnEnded(a : Player, s : Map<Coordinate, String>)
    + onCellUpdated(defender : Player, coord : Coordinate)
    + onShipSunk(defender : Player)
    + onBlackHolHit(defender : Player)
    + onStormHit(attacker : Player)
}

interface model.GridEntity {
    + onHit(attacker : Player, defender : Player, x : Integer, y : Integer, segmentIndex : Integer)
    + EntityType getType()
    + Integer getSize()
    + boolean isSunk()
    + registerToGrid(grid : Grid)
}

interface model.IslandListener {
    + notifyPlaceIslandEntity(entity : Trap, player : Player)
    + notifyWeaponFind(weaponType : EntityType)
    + notifyTrapWrongPlacement()
}

enum model.EntityType {
    + AIRCRAFT_CARRIER
    + CRUISER
    + SUBMARINE
    + TORPEDO
    + DESTROYER
    + BLACK_HOLE
    + STORM
    + BOMB
    + SONAR
    + MISSILE
    + NEW_BLACKHOLE
    + NEW_STORM
    + NEW_BOMB
    + NEW_SONAR
}

' ----------------------------
' Relations Player
' ----------------------------
Player "1" *--> "1\n ownGrid" Grid
Player "1" *--> "1\n shotGrid" Grid
Player "1" *--> "*\n m_availableWeapons" Weapon
Player "1" *--> "1\n m_weaponFacto" WeaponFactory
Player "1" *--> "1\n m_trapFacto" TrapFactory
Player --> ScanResult : <<use>>
Player --> Coordinate : <<use>>
Player --> GameConfiguration : <<use>>
Player --> Boat : <<use>>
Player --> Trap : <<use>>
Player --> EntityType : <<use>>

HumanPlayer --> Player : <<inherit>>
ComputerPlayer --> Player : <<inherit>>
ComputerPlayer --> Coordinate : <<use>>
ComputerPlayer --> Weapon : <<use>>
ComputerPlayer --> GameConfiguration : <<use>>

' ----------------------------
' Relations Grid
' ----------------------------
Grid "1" *--> "*\n m_cells" Cell
Grid "1" *--> "1\n m_trapFactory" TrapFactory
Grid "1" *--> "1\n m_islandItemFactory" IslandItemFactory
Grid "1" *--> "1\n m_boatFactory" BoatFactory
Grid "1" *--> "0..*\n m_ownBoats" Boat : <<contain>>
Grid --> Coordinate : <<use>>
Grid --> GridEntity : <<use>>
Grid --> EntityType : <<use>>

Cell --> GridEntity : <<contain>>
Cell --> Coordinate : <<use>>
Cell --> EntityType : <<use>>
Cell "1" *--> "1\n parentGrid" Grid

' ----------------------------
' Relations Boat
' ----------------------------
Boat <|-- AirCraftCarrier
Boat <|-- Cruiser
Boat <|-- Destroyer
Boat <|-- Submarine
Boat <|-- Torpedo
BoatFactory --> AirCraftCarrier : <<create>>
BoatFactory --> Cruiser : <<create>>
BoatFactory --> Destroyer : <<create>>
BoatFactory --> Submarine : <<create>>
BoatFactory --> Torpedo : <<create>>

' ----------------------------
' Relations Trap
' ----------------------------
Trap <|-- BlackHole
Trap <|-- Storm
TrapFactory --> BlackHole : <<create>>
TrapFactory --> Storm : <<create>>

NewBlackHole --> TrapFactory : <<use>>
NewStorm --> TrapFactory : <<use>>
NewBomb --> WeaponFactory : <<use>>
NewSonar --> WeaponFactory : <<use>>

' ----------------------------
' Relations Weapon
' ----------------------------
Weapon <|-- Sonar
Weapon <|-- Bombe
Weapon <|-- Missile
WeaponFactory --> Sonar : <<create>>
WeaponFactory --> Bombe : <<create>>
WeaponFactory --> Missile : <<create>>

' ----------------------------
' Relations Game
' ----------------------------
Game "1" *--> "1\n m_humanPlayer" HumanPlayer
Game "1" *--> "1\n m_computerPlayer" ComputerPlayer
Game "1" --> "1" GameConfiguration : <<create>>
Game "1" --> "*\n m_listeners" GameListener : <<notify>>
Game --> Weapon : <<use>>
Game --> ScanResult : <<use>>
Game --> Coordinate : <<use>>
Game --> Player : <<use>>
Game --> Boat : <<use>>
Game --> Trap : <<use>>

' ----------------------------
' Relations IslandItemFactory
' ----------------------------
IslandItemFactory --> NewStorm : <<create>>
IslandItemFactory --> NewSonar : <<create>>
IslandItemFactory --> NewBomb : <<create>>
IslandItemFactory --> NewBlackHole : <<create>>

' ----------------------------
' Relations Coordinate & ScanResult
' ----------------------------
ScanResult --> Coordinate : <<use>>
ScanResult --> EntityType : <<use>>
Coordinate --> Integer : <<use>>

' ----------------------------
' Relations autres interfaces
' ----------------------------
GameMediator <|.. Game
IslandListener --> Player : <<notify>>


@enduml